language: java
jdk: openjdk11

dist: bionic

services:
  - docker
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS chess_online_dev;'
  - docker run -d -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest -p 4369:4369 -p 5671:5671 -p 5672:5672 -p 15672:15672 -p 61613:61613  itzg/rabbitmq-stomp

script:
  - ./gradlew test build