spring:
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost/chess_online_dev?useSSL=false&serverTimezone=Europe/Stockholm
    username: root

  rabbitmq:
    host: 'localhost'
    username: 'guest'
    password: 'guest'

logging:
  level:
    org:
      springframework: INFO
    com:
      company: DEBUG