spring:
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost/chess_online_dev?useSSL=false&serverTimezone=Europe/Stockholm
    username: root

logging:
  level:
    org:
      springframework: INFO
    com:
      company: DEBUG